version: '3.1'

services:
  tracker-exporter:
    container_name: tracker-exporter
    hostname: tracker-exporter
    restart: unless-stopped
    build: .
    volumes:
      - ./.env:/opt/exporter/.env:ro
    command: |
      tracker-exporter --env-file /opt/exporter/.env
