version: '3.1'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    hostname: clickhouse
    restart: unless-stopped
    volumes:
      - "./clickhouse:/var/lib/clickhouse"
    ports:
      - "9000:9000"
      - "8123:8123"

  tracker-exporter:
    build: .
    container_name: tracker-exporter
    hostname: tracker-exporter
    restart: unless-stopped
    environment:
      EXPORTER_CHANGELOG_EXPORT_ENABLED: "false"
      EXPORTER_TRACKER__TOKEN: ${TRACKER_TOKEN}
      EXPORTER_TRACKER__CLOUD_ORG_ID: ${TRACKER_ORG_ID}
      EXPORTER_CLICKHOUSE__HOST: clickhouse
      EXPORTER_CLICKHOUSE__PORT: 8123
      EXPORTER_CLICKHOUSE__ENABLE_UPLOAD: "true"
      EXPORTER_STATEFUL: "true"
      EXPORTER_STATEFUL_INITIAL_RANGE: "1d"
      EXPORTER_STATE__STORAGE: jsonfile
      EXPORTER_STATE__JSONFILE_STRATEGY: local
      EXPORTER_STATE__JSONFILE_PATH: /opt/exporter/state.json
    volumes:
      - "./exporter:/opt/exporter:rw"
    depends_on:
      - clickhouse
