---
- name: clickhouse - check proxy binary exists
  stat:
    path: "{{ clickhouse_proxy_binary_dir }}/{{ clickhouse_proxy_binary_name }}"
  register: clickhouse_proxy_binary

- block:
  - name: clickhouse - download proxy binary
    get_url:
      url: "https://github.com/ContentSquare/chproxy/releases/download/v{{ clickhouse_proxy_version }}/chproxy_{{ clickhouse_proxy_version }}_linux_{{ system_arch }}.tar.gz"
      dest: "/tmp/chproxy-{{ clickhouse_proxy_version }}.linux-{{ system_arch }}.tar.gz"
      mode: "0644"
    register: download_binary
    until: download_binary is succeeded
    retries: 5
    delay: 2
    delegate_to: localhost

  - name: clickhouse - unpack proxy binary
    become: false
    unarchive:
      src: "/tmp/chproxy-{{ clickhouse_proxy_version }}.linux-{{ system_arch }}.tar.gz"
      dest: "/tmp"
      creates: "/tmp/chproxy-{{ clickhouse_proxy_version }}.linux-{{ system_arch }}/{{ clickhouse_proxy_binary_name }}"
    delegate_to: localhost
    check_mode: false

  - name: clickhouse - propagate proxy binary
    copy:
      src: "/tmp/chproxy"
      dest: "{{ clickhouse_proxy_binary_dir }}/{{ clickhouse_proxy_binary_name }}"
      mode: "0755"
      owner: "{{ clickhouse_general_owner }}"
      group: "{{ clickhouse_general_owner }}"

  when: not clickhouse_proxy_binary.stat.exists

- name: clickhouse - create cache dir for proxy
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ clickhouse_proxy_base_cache_dir }}"
    - "{{ clickhouse_proxy_cache_dir }}"

- block:
  - name: clickhouse - configure proxy systemd service
    template:
      src: templates/proxy/chproxy.service.j2
      dest: "{{ clickhouse_proxy_systemd_service_dir }}/{{ clickhouse_proxy_service_name }}.service"
      mode: "0644"
      owner: "{{ clickhouse_general_owner }}"
      group: "{{ clickhouse_general_owner }}"

  - name: clickhouse - configure proxy
    template:
      src: templates/proxy/config.yml.j2
      dest: "{{ clickhouse_config_dir }}/proxy.yml"
      owner: "{{ clickhouse_general_owner }}"
      group: "{{ clickhouse_general_owner }}"
      mode: "0644"
    notify:
      clickhouse - restart proxy service

- name: clickhouse - start proxy
  systemd:
    daemon_reload: true
    name: "{{ clickhouse_proxy_service_name }}"
    enabled: true
    state: started
  when: not ansible_check_mode
