---
- name: clickhouse - create clickhouse dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ clickhouse_system_user }}"
    group: "{{ clickhouse_system_group }}"
  with_items:
    - "{{ clickhouse_config_dir }}"
    - "{{ clickhouse_data_dir }}"
  tags:
    - clickhouse-install

- name: clickhouse - server configuration
  template:
    src: templates/server.xml.j2
    dest: "{{ clickhouse_config_dir }}/config.xml"
    mode: "0644"
  notify:
    - clickhouse - restart docker composition
  tags:
    - clickhouse-config

- name: clickhouse - users configuration
  template:
    src: templates/users.xml.j2
    dest: "{{ clickhouse_config_dir }}/users.xml"
    mode: "0644"
  notify:
    - clickhouse - restart docker composition
  tags:
    - clickhouse-users
