---

- import_tasks: preflight.yml
  tags:
    - clickhouse
    - clickhouse-install
    - clickhouse-config

- import_tasks: configure.yml
  tags:
    - clickhouse
    - clickhouse-install
    - clickhouse-config

- import_tasks: install.yml
  tags:
    - clickhouse
    - clickhouse-install
    - clickhouse-docker-config

- import_tasks: chproxy.yml
  tags:
    - clickhouse
    - clickhouse-install
    - clickhouse-proxy
  when: clickhouse_proxy_enabled
