---
- name: clickhouse - create base directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ clickhouse_general_owner }}"
    group: "{{ clickhouse_general_owner }}"
  with_items:
    - "{{ clickhouse_base_root_dir }}"
    - "{{ clickhouse_base_config_dir }}"
    - "{{ clickhouse_base_data_dir }}"
  tags:
    - clickhouse-install
    - clickhouse-config

- name: clickhouse - create group
  group:
    name: "{{ clickhouse_system_group }}"
    state: present
    system: true
  when: clickhouse_system_group != "root"

- name: clickhouse - create user
  user:
    name: "{{ clickhouse_system_user }}"
    groups: "{{ clickhouse_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  when: clickhouse_system_user != "root"
