---
clickhouse_general_owner: root
clickhouse_system_user: root
clickhouse_system_group: root

clickhouse_base_root_dir: /opt
clickhouse_base_config_dir: "{{ clickhouse_base_root_dir }}/conf"
clickhouse_base_data_dir: "{{ clickhouse_base_root_dir }}/data"

clickhouse_data_dir: "{{ clickhouse_base_data_dir }}/clickhouse"
clickhouse_config_dir: "{{ clickhouse_base_config_dir }}/clickhouse"

clickhouse_version: 22.1.3.7
clickhouse_prompt: "{{ inventory_hostname }} - internal agile"
clickhouse_listen_address: 0.0.0.0
clickhouse_listen_http_port: 8123
clickhouse_listen_tcp_port: 9000

# $clickhouse_zookeeper_hosts: (dict)
#   - fqdn: zoo1.example.com
#     port: 2181
#   - fqdn: ...
clickhouse_zookeeper_hosts: {}
clickhouse_zookeeper_enabled: false

clickhouse_docker_limit_cpu: 4
clickhouse_docker_limit_memory: 12gb

clickhouse_max_concurrent_queries: 300
clickhouse_max_connections: 4096

clickhouse_users:
  default:
    username: default
    password: defaultpassword  # CHANGEME
    profile: default
    quota: default
  exporter:
    username: exporter
    password: exporterpassword  # CHANGEME
    profile: default
    quota: default
  readonly:
    username: readonly
    password: readonlypassword  # CHANGEME
    profile: readonly
    quota: default

clickhouse_proxy_enabled: true
clickhouse_proxy_version: 1.16.0
clickhouse_proxy_binary_dir: /usr/local/bin
clickhouse_proxy_systemd_service_dir: /lib/systemd/system
clickhouse_proxy_base_cache_dir: "{{ clickhouse_base_data_dir }}/chproxy"
clickhouse_proxy_cache_dir: "{{ clickhouse_proxy_base_cache_dir }}/cache"
clickhouse_proxy_binary_name: chproxy
clickhouse_proxy_config_dir: "{{ clickhouse_config_dir }}/proxy.yml"
clickhouse_proxy_service_name: chproxy
clickhouse_proxy_listen_address: 0.0.0.0
clickhouse_proxy_listen_http_port: 8080
clickhouse_proxy_allowed_users:
  - readonly
clickhouse_proxy_allowed_networks:
  - 178.154.242.176/28  # DataLens
  - 178.154.242.192/28  # DataLens
  - 178.154.242.208/28  # DataLens
  - 178.154.242.128/28  # DataLens
  - 178.154.242.144/28  # DataLens
  - 178.154.242.160/28  # DataLens
  - 127.0.0.1
